# File: lcm_sandbox/core/artifact_capture.py
# Description: Phase 6 — capture artifacts from a stopped/finishing sandbox
#              container and the worktree it produced commits in. Implements
#              SANDBOX-DETAILED-FLOW.md STEP 6.1 through 6.7 (filesystem
#              archival only; DB store + S3 are Phase 5 work).
# Author: Libor Ballaty <libor@arionetworks.com>
# Created: 2026-06-17

"""Phase 6: artifact capture.

Output layout per sandbox (under ``~/.lcm-sandbox/artifacts/<sandbox_id>/``):

::

  manifest.json        # capture summary + stats
  commits.json         # list of new commits since the baseline (one per line is OK)
  diff.patch           # `git diff <baseline>..HEAD`
  stdout.log           # `docker logs --stdout <container>` if available
  stderr.log           # `docker logs --stderr <container>` if available
  agent.log            # combined docker logs (fallback when stdout/stderr split fails)

The capturer is intentionally tolerant — partial results are useful, so any
single step's failure is logged and recorded in the manifest rather than
raising.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from lcm_sandbox.exceptions import ArtifactCaptureError
from lcm_sandbox.models import SandboxConfig, WorktreeBaseline
from lcm_sandbox.utils.logger import get_logger
from lcm_sandbox.utils.shell import run

logger = get_logger(__name__)

DEFAULT_ARTIFACTS_ROOT = Path.home() / ".lcm-sandbox" / "artifacts"


class CommitRecord(BaseModel):
    sha: str
    author: str
    timestamp: str
    subject: str


class ArtifactCaptureResult(BaseModel):
    """Summary returned to the caller of `capture_artifacts`."""

    sandbox_id: str
    artifact_dir: Path
    captured_at: datetime
    status: Literal["captured", "partial", "no_container"]
    exit_code: int | None = None
    container_present: bool = False
    new_commit_count: int = 0
    final_head: str | None = None
    new_commits: list[CommitRecord] = Field(default_factory=list)
    diff_path: Path | None = None
    stdout_log_path: Path | None = None
    stderr_log_path: Path | None = None
    manifest_path: Path | None = None
    warnings: list[str] = Field(default_factory=list)


# ── Helpers ──────────────────────────────────────────────────────────────────


def _ensure_root_layout(root: Path) -> None:
    """Make sure ~/.lcm-sandbox/artifacts/ exists and has a README on first use."""
    root.mkdir(parents=True, exist_ok=True)
    readme = root / "README.md"
    if not readme.exists():
        readme.write_text(
            "# LCM-Sandbox artifact archive\n\n"
            "Each subdirectory is named after a `sandbox_id` and contains the\n"
            "capture output produced by `lcm-sandbox cleanup` / `lcm-sandbox\n"
            "capture` for that run:\n\n"
            "- `manifest.json` — capture summary + stats\n"
            "- `commits.json` — new commits since the worktree baseline\n"
            "- `diff.patch` — `git diff <baseline>..HEAD`\n"
            "- `stdout.log` / `stderr.log` — container output (split when\n"
            "  the docker daemon supports it; otherwise see `agent.log`)\n"
            "- `agent.log` — combined docker logs (fallback)\n\n"
            "Generated by `lcm_sandbox.core.artifact_capture` — do not edit.\n"
        )


def _container_exit_code(container_name: str) -> tuple[int | None, bool]:
    """Return (exit_code, container_present). Tolerant of missing container."""
    res = run(["docker", "inspect", "-f", "{{.State.ExitCode}}", container_name])
    if res.returncode != 0:
        return None, False
    try:
        return int(res.stdout.strip()), True
    except ValueError:
        return None, True


def _write_container_logs(container_name: str, out_dir: Path) -> tuple[Path | None, Path | None, list[str]]:
    """Capture docker logs as best we can. Returns (stdout_path, stderr_path, warnings)."""
    warnings: list[str] = []
    stdout_path = out_dir / "stdout.log"
    stderr_path = out_dir / "stderr.log"

    # Try splitting stdout/stderr. `docker logs` defaults to interleaved; passing
    # the streams to separate files requires running it twice with -- the same
    # binary but redirecting at the shell level. We capture via subprocess
    # directly so we can route streams cleanly.
    try:
        with stdout_path.open("wb") as fo, stderr_path.open("wb") as fe:
            proc = subprocess.run(
                ["docker", "logs", container_name],
                stdout=fo,
                stderr=fe,
                check=False,
                timeout=60,
            )
        if proc.returncode != 0:
            warnings.append(f"docker logs exited {proc.returncode}")
    except FileNotFoundError:
        warnings.append("docker binary not on PATH; logs not captured")
        return None, None, warnings
    except subprocess.TimeoutExpired:
        warnings.append("docker logs timed out after 60s")

    # Always also write a combined fallback log; tools that only care about
    # interleaved order use this.
    combined = out_dir / "agent.log"
    try:
        combined_proc = subprocess.run(
            ["docker", "logs", container_name],
            capture_output=True,
            check=False,
            timeout=60,
        )
        combined.write_bytes(combined_proc.stdout + combined_proc.stderr)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return stdout_path if stdout_path.exists() else None, stderr_path if stderr_path.exists() else None, warnings


def _capture_git_state(
    worktree_path: Path,
    baseline_sha: str,
    out_dir: Path,
) -> tuple[str | None, list[CommitRecord], Path | None, list[str]]:
    """Returns (final_head, new_commits, diff_path, warnings)."""
    warnings: list[str] = []
    if not (worktree_path / ".git").exists():
        warnings.append(f"{worktree_path} is not a git working tree; skipping git capture")
        return None, [], None, warnings

    head_res = run(["git", "-C", str(worktree_path), "rev-parse", "HEAD"])
    final_head = head_res.stdout.strip() if head_res.returncode == 0 else None
    if not final_head:
        warnings.append("git rev-parse HEAD failed")
        return None, [], None, warnings

    # New commits (oldest → newest).
    log_res = run([
        "git", "-C", str(worktree_path), "log",
        f"{baseline_sha}..HEAD",
        "--format=%H%x1f%an%x1f%aI%x1f%s",
    ])
    commits: list[CommitRecord] = []
    if log_res.returncode == 0:
        for line in log_res.stdout.splitlines():
            if not line.strip():
                continue
            parts = line.split("\x1f")
            if len(parts) != 4:
                warnings.append(f"unparseable git log line: {line!r}")
                continue
            sha, author, ts, subject = parts
            commits.append(CommitRecord(sha=sha, author=author, timestamp=ts, subject=subject))
    else:
        warnings.append(f"git log {baseline_sha}..HEAD failed: {log_res.stderr.strip()}")

    # Diff patch.
    diff_path = out_dir / "diff.patch"
    diff_res = run([
        "git", "-C", str(worktree_path), "diff",
        f"{baseline_sha}..HEAD",
    ])
    if diff_res.returncode == 0:
        diff_path.write_text(diff_res.stdout)
    else:
        warnings.append(f"git diff failed: {diff_res.stderr.strip()}")
        diff_path = None

    return final_head, commits, diff_path, warnings


# ── Public API ───────────────────────────────────────────────────────────────


def capture_artifacts(
    sandbox_config: SandboxConfig,
    *,
    baseline: WorktreeBaseline,
    container_name: str | None = None,
    artifacts_root: Path | None = None,
) -> ArtifactCaptureResult:
    """Capture artifacts for a sandbox run.

    The container must be stopped or stoppable. The caller is responsible for
    container teardown via `cleanup`; this function is read-only with respect
    to the container.

    Args:
        sandbox_config: the SandboxConfig used to launch the run.
        baseline: worktree baseline taken pre-launch (Phase 1).
        container_name: docker container name; defaults to sandbox_config.run_id.
        artifacts_root: override for the archive root (default: ~/.lcm-sandbox/artifacts).
    """
    name = container_name or sandbox_config.run_id
    root = artifacts_root or DEFAULT_ARTIFACTS_ROOT
    _ensure_root_layout(root)

    out_dir = root / sandbox_config.run_id
    out_dir.mkdir(parents=True, exist_ok=True)

    warnings: list[str] = []
    captured_at = datetime.now(timezone.utc)

    exit_code, container_present = _container_exit_code(name)
    if not container_present:
        warnings.append(f"container {name} not found at capture time")

    stdout_path = stderr_path = None
    if container_present:
        stdout_path, stderr_path, log_warnings = _write_container_logs(name, out_dir)
        warnings.extend(log_warnings)

    worktree_path = Path(sandbox_config.repo_path)
    final_head, new_commits, diff_path, git_warnings = _capture_git_state(
        worktree_path, baseline.latest_commit, out_dir,
    )
    warnings.extend(git_warnings)

    commits_path = out_dir / "commits.json"
    commits_path.write_text(
        json.dumps([c.model_dump() for c in new_commits], indent=2) + "\n"
    )

    status: Literal["captured", "partial", "no_container"]
    if not container_present and not final_head:
        status = "no_container"
    elif warnings:
        status = "partial"
    else:
        status = "captured"

    manifest_path = out_dir / "manifest.json"
    manifest = {
        "sandbox_id": sandbox_config.run_id,
        "plan_id": sandbox_config.plan_id,
        "branch_name": sandbox_config.branch_name,
        "baseline_commit": baseline.latest_commit,
        "final_head": final_head,
        "new_commit_count": len(new_commits),
        "container_name": name,
        "container_present": container_present,
        "exit_code": exit_code,
        "captured_at": captured_at.isoformat(),
        "status": status,
        "warnings": warnings,
        "artifact_files": {
            "diff": str(diff_path) if diff_path else None,
            "commits": str(commits_path),
            "stdout": str(stdout_path) if stdout_path else None,
            "stderr": str(stderr_path) if stderr_path else None,
            "agent_log": str(out_dir / "agent.log") if (out_dir / "agent.log").exists() else None,
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    logger.info(
        "artifact_capture_done",
        extra={
            "sandbox_id": sandbox_config.run_id,
            "phase": 6,
            "step": "6.7",
            "status": status,
            "new_commits": len(new_commits),
            "artifact_dir": str(out_dir),
        },
    )

    return ArtifactCaptureResult(
        sandbox_id=sandbox_config.run_id,
        artifact_dir=out_dir,
        captured_at=captured_at,
        status=status,
        exit_code=exit_code,
        container_present=container_present,
        new_commit_count=len(new_commits),
        final_head=final_head,
        new_commits=new_commits,
        diff_path=diff_path,
        stdout_log_path=stdout_path,
        stderr_log_path=stderr_path,
        manifest_path=manifest_path,
        warnings=warnings,
    )


def cleanup_sandbox(
    sandbox_config: SandboxConfig,
    *,
    container_name: str | None = None,
    keep_artifacts: bool = True,
    remove_worktree: bool = True,
    artifacts_root: Path | None = None,
) -> dict:
    """Remove the container + (optionally) the worktree + (optionally) artifacts.

    Idempotent: re-running after a successful cleanup is a no-op that returns
    a "already cleaned up" payload instead of raising.

    Args:
        sandbox_config: the SandboxConfig used to launch the run.
        container_name: docker container name; defaults to sandbox_config.run_id.
        keep_artifacts: when False, also wipe the per-run artifact dir.
        remove_worktree: when False, leave the host worktree on disk.
        artifacts_root: override for the archive root.
    """
    name = container_name or sandbox_config.run_id
    root = artifacts_root or DEFAULT_ARTIFACTS_ROOT
    actions: dict[str, str] = {}

    # Container teardown.
    inspect = run(["docker", "inspect", "-f", "{{.State.Status}}", name])
    if inspect.returncode == 0:
        run(["docker", "stop", name])
        rm = run(["docker", "rm", "-f", name])
        actions["container"] = "removed" if rm.returncode == 0 else f"rm-failed: {rm.stderr.strip()}"
    else:
        actions["container"] = "already-absent"

    # Worktree teardown — only `git worktree remove`; never `rm -rf` a path.
    if remove_worktree:
        wt = Path(sandbox_config.repo_path)
        if wt.exists():
            wt_res = run(["git", "worktree", "remove", "--force", str(wt)])
            if wt_res.returncode == 0:
                actions["worktree"] = "removed"
            else:
                actions["worktree"] = f"remove-failed: {wt_res.stderr.strip()}"
        else:
            actions["worktree"] = "already-absent"
    else:
        actions["worktree"] = "kept"

    # Artifacts.
    art_dir = root / sandbox_config.run_id
    if art_dir.exists():
        if keep_artifacts:
            actions["artifacts"] = f"kept at {art_dir}"
        else:
            shutil.rmtree(art_dir)
            actions["artifacts"] = "removed"
    else:
        actions["artifacts"] = "none"

    return {
        "sandbox_id": sandbox_config.run_id,
        "actions": actions,
        "cleaned_at": datetime.now(timezone.utc).isoformat(),
    }
